trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '$(Devops_Project)'
    pipeline: '$(Devops_Pipeline)'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/master'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '(Get-Content index.html).replace(''%%GTAG_ID%%'', $env:GTAG_ID) | Set-Content index.html'
    workingDirectory: '$(System.ArtifactsDirectory)/drop'
  displayName: Replacing Google Analytics tag
  

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '$(FTPServerUrl)'
    username: '$(FTPUsername)'
    password: '$(FTPPassword)'
    rootDirectory: '$(System.ArtifactsDirectory)/drop'
    filePatterns: '**'
    remoteDirectory: '/'
    clean: false
    cleanContents: false
    preservePaths: true
    trustSSL: false